name: Post
description: A post for Yixuan Wang's blog.
labels: ["+"]
body:
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: frontmatter
    attributes:
      label: YAML Frontmatter
      description: Metadata of the post.
      render: YAML
      value: |
        title: Title
        date: Current Time (ISO Format)
        genre: article | sheet | note
        category: Category
        tags:
          - tag
        keywords:
          - optional
        lang: en
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: excerpt
    attributes:
      label: Excerpt
      description: A short summary of the post.
      placeholder: Lorem ipsum dolor sit amet.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "\n<!-- more -->\n\n"
  - type: textarea
    id: more
    attributes:
      label: Some More
      description: The first part of of the post.
      placeholder: Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
