name: "Dispatch Contents Update"

on:
  push:
    branches: [ master ]

jobs:
  dispatch-contents-update:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Contents Update Event
        if: ${{ !startsWith(github.event.commits[0].message, '!') }}
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: Yixuan-Wang/blog
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: contents-update
          client-payload: |
            {
              "message": "${{ github.event.commits[0].message }}",
              "name": "${{ github.event.commits[0].author.name }}",
              "email": "${{ github.event.commits[0].author.email }}"
            }
